<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }
        .project-info {
            margin-bottom: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section-title {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 10px;
        }
        .logs {
            margin-bottom: 30px;
        }
        .log-item {
            margin-bottom: 15px;
            padding: 10px;
            background: #f9fafb;
        }
        .log-date {
            font-weight: bold;
            color: #4b5563;
        }
        .log-type {
            display: inline-block;
            padding: 2px 8px;
            background: #dbeafe;
            color: #1e40af;
            border-radius: 4px;
            font-size: 12px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report->title }}</h1>
        <p>{{ $report->content }}</p>
    </div>

    <div class="project-info">
        <h2>Project: {{ $report->project->name }}</h2>
        <p>Generated on: {{ now()->format('F j, Y') }}</p>
    </div>

    @if($report->seoLogs->count() > 0)
        <div class="logs">
            <h3>SEO Activities</h3>
            @foreach($report->seoLogs as $log)
                <div class="log-item">
                    <div class="log-date">{{ $log->work_date }}</div>
                    <span class="log-type">{{ $log->work_type }}</span>
                    <p>{{ $log->description }}</p>
                </div>
            @endforeach
        </div>
    @endif

    @if($report->sections->count() > 0)
        @foreach($report->sections->sortBy('priority') as $section)
            <div class="section">
                <div class="section-title">{{ $section->title }}</div>
                <div class="section-content">{{ $section->content }}</div>
            </div>
        @endforeach
    @endif

    <div class="footer">
        <p>Generated by SEO Dashboard</p>
        <p>© {{ date('Y') }} All rights reserved.</p>
    </div>
</body>
</html> 